name = "agent-test"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]
main = "src/server.ts"

assets = { directory = "./public/" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

  # { name = "AssistantAgent", class_name = "AssistantAgent" }
# ]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Chat"]


[[d1_databases]]
binding = "DB" # This is how you'll reference your DB in your code
database_name = "agent-test"
database_id = "3a7c6f92-ffff-ffff-ffff-c2e9b7d63a8d"
